name: Build Custom Spider
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add execute permission to gradlew
        run: chmod +x gradlew

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Build APK
        run: |
          ./gradlew assembleRelease

      - name: Clean up previous build artifacts
        run: |
          rm -f jar/xiaoya_proxy.jar
          rm -rf jar/spider.jar/smali/com/github/catvod
          rm -rf jar/spider.jar/smali/org/slf4j
          rm -rf jar/spider.jar/smali/com/github/catvod/spider
          mkdir -p jar/spider.jar/smali/com/github/catvod
          mkdir -p jar/spider.jar/smali/org/slf4j
          mkdir -p jar/spider.jar/smali/com/github/catvod/spider

      - name: Decode APK
        run: |
          java -jar jar/3rd/apktool_2.11.0.jar d -f --only-main-classes ./app/build/outputs/apk/release/app-release-unsigned.apk -o jar/Smali_classes

      - name: List source directories
        run: |
          ls -l jar/Smali_classes/smali/com/github/catvod/spider
          ls -l jar/Smali_classes/smali/com/github/catvod/js
          ls -l jar/Smali_classes/smali/org/slf4j

      - name: Move smali files
        run: |
          mv jar/Smali_classes/smali/com/github/catvod/spider jar/spider.jar/smali/com/github/catvod/spider
          mv jar/Smali_classes/smali/com/github/catvod/js jar/spider.jar/smali/com/github/catvod/js
          mv jar/Smali_classes/smali/org/slf4j jar/spider.jar/smali/org/slf4j

      - name: Build JAR
        run: |
          java -jar jar/3rd/apktool_2.11.0.jar b jar/spider.jar -c

      - name: Rename and generate MD5
        run: |
          mkdir -p jar
          mv jar/spider.jar/dist/dex.jar jar/xiaoya_proxy.jar
          md5sum jar/xiaoya_proxy.jar | cut -d ' ' -f 1 > jar/xiaoya_proxy.jar.md5

      - name: Clean up temporary files
        run: |
          rm -rf jar/spider.jar/build
          rm -rf jar/spider.jar/smali
          rm -rf jar/spider.jar/dist
          rm -rf jar/Smali_classes

      - name: Commit files to jar directory
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add jar/
          git commit -m "Add xiaoya_proxy.jar and xiaoya_proxy.jar.md5"
          git push
